<?php

use yii\db\Migration;

class m000000_300004_operator_geo extends Migration
{
    public function safeUp()
    {
        $this->createTable('operator_geo', [
            'id' => $this->primaryKey(),
            'user_id' => $this->integer(4),
            'country_id' => $this->integer(4),
            'is_active' => $this->boolean(),
        ]);

        $this->createIndex('Index-userId_countryId', 'operator_geo', ['user_id', 'country_id'], true);

        parent::safeUp(); // TODO: Change the autogenerated stub
    }

    public function safeDown()
    {
        $this->dropIndex('Index-userId_countryId', 'operator_geo');
        $this->dropTable('operator_geo');
    }
}
