-- Egypt 199
INSERT INTO geo_region (region_name, geo_id) VALUES ('Ain Sokhna', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Alexandria', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Aswan', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Asyut', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Behira', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Benisuif', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Cairo', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Canal', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Damanhour', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Dommyat', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('El Sharkia', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Fayoum', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Giza', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Hurghada', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Ismailya', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Kafr el Sheikh', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Luxor', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Mahla', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Mansoura', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Marsa Matrouh', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Minya', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Monofia', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Port Said', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Quena', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Quliob', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Red sea', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Safaga', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Sharm el-sheikh', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Sinai', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Souhag', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Suez', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Tanta', 199);
INSERT INTO geo_region (region_name, geo_id) VALUES ('Upper Egypt', 199);