<?php

return [
    require(__DIR__ . '/stock.php'),
    require(__DIR__ . '/product-sku.php'),
    require(__DIR__ . '/offer-sku.php'),
    require(__DIR__ . '/user.php'),
    require(__DIR__ . '/setting.php'),
    require(__DIR__ . '/product.php'),
    require(__DIR__ . '/offer.php'),
    require(__DIR__ . '/advert-target.php'),
    require(__DIR__ . '/wm-target.php'),
    require(__DIR__ . '/order.php'),
    require(__DIR__ . '/order-status.php'),
    require(__DIR__ . '/order-sku.php'),
    require(__DIR__ . '/offer-landing.php'),
    require(__DIR__ . '/callcenter.php'),
    require(__DIR__ . '/customer.php'),
    require(__DIR__ . '/delivery.php'),
    require(__DIR__ . '/data-list.php'),
    require(__DIR__ . '/export.php'),
    require(__DIR__ . '/requests.php'),
    require(__DIR__ . '/finance.php'),
    require(__DIR__ . '/finstrip.php'),
    require(__DIR__ . '/requests.php'),
    require(__DIR__ . '/advert-money.php'),
    require(__DIR__ . '/checkouts.php'),
    require(__DIR__ . '/load.php'),
    require(__DIR__ . '/statistic.php'),
    require(__DIR__ . '/sse.php'),
    require(__DIR__ . '/notify.php'),
    require(__DIR__ . '/import.php'),
    require(__DIR__ . '/contact.php'),
    require(__DIR__ . '/blacklist.php'),
    require(__DIR__ . '/delivery-sticker.php'),
    require(__DIR__ . '/test.php'),
];