<?php

namespace common\models\landing;

use common\models\finance\Currency;
use common\models\geo\Geo;
use common\models\offer\Offer;
use common\services\cache\CacheCommonSrv;
use Yii;

/**
 * This is the model class for table "landing_geo".
 *

 * @property integer $geo_id
 * @property integer $offer_geo_price_id
 * @property integer $offer_id
 * @property integer $old_price
 * @property integer $new_price
 * @property integer $discount
 * @property integer $currency_id
 *
 * @property Currency $currency
 * @property Geo $geo
 * @property Landing $landing
 */
class OfferGeoPrice extends \yii\db\ActiveRecord
{
    public $offer_hash;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_geo_price';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'geo_id', 'currency_id', 'new_price'], 'required'],
            [['offer_id', 'geo_id', 'currency_id'], 'integer'],
            [['old_price', 'new_price', 'discount'], 'safe'],
            [['currency_id'], 'exist', 'skipOnError' => true, 'targetClass' => Currency::className(), 'targetAttribute' => ['currency_id' => 'currency_id']],
            [['geo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Geo::className(), 'targetAttribute' => ['geo_id' => 'geo_id']],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'offer_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_geo_price_id' => 'Offer Geo Price ID',
            'geo_id' => 'Geo ID',
            'offer_id' => 'Offer ID',
            'old_price' => 'Old Price',
            'new_price' => 'New Price',
            'discount' => 'Discount',
            'currency_id' => 'Currency ID',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
//        $landings = Landing::find()->where(['offer_id' => $this->offer_id])->all();
//
//        $cacheSrv = new CacheCommonSrv();
//        foreach ($landings as $landing)
//        {
//            $data = [
//                'table' => 'offer_geo_price',
//                [
//                    'field' => 'geo_id',
//                    'value' => $this->geo_id,
//                ],
//                [
//                    'field' => 'landing_id',
//                    'value' => $landing->landing_id,
//
//                ],
//            ];
//
//            $cacheSrv->flushRecordsByKeyPart($data);
//        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurrency()
    {
        return $this->hasOne(Currency::className(), ['currency_id' => 'currency_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGeo()
    {
        return $this->hasOne(Geo::className(), ['geo_id' => 'geo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(Offer::className(), ['offer_id' => 'offer_id']);
    }
}
